Feature form
serdg0/re_former pull request #1
Opened 2019-09-04 22:14 UTC by serdg0

2019-09-06 15:57 UTC, mcrd25 requested changes
# Great Job so far

Hi, @serdg0  and @MephistoDevelop 👋,

Okay team, let's get into this review by highlighting the awesome things you did
- Your README is very informative.  I commend you for the effort you put into it 👏. If you'd like to improve the visuals of your README checkout this [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for useful syntax. 
- You were clever in some areas 😛 
- Did the basics well and stuck to the task at hand!


## Required Changes
- Handle your .gitignore issues. If you are having time removing already committed check out my gist on the topic and you should be fine. Just click [here](https://gist.github.com/mcrd25/1b2718054b65f4720fa582c6a4032217). **Files not related to the project should not be committed**

## Additional Suggestions [OPTIONAL]
- Maybe you can create a form partial and reuse it for `new` and `edit`

## Conclusion
*This project is well done! 👍 There is only one required issue for you to address above ⬆️. However, I do recommend that you Address some of the OPTIONAL suggestions*

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-09-06 15:57 UTC, mcrd25 commented on .idea/.generators
>  2. Remove generators
The .idea folder should be added to your .gitignore file. Please add it before the next review. 🙂

2019-09-06 15:57 UTC, mcrd25 commented on app/models/user.rb
> +  validates :email, presence: true
Maybe you can add additional validation for uniqueness. **[OPTIONAL]**
I can currently create multiple users with the same email and username. see image below
![Screen Shot 2019-09-06 at 8 57 00 AM](https://user-images.githubusercontent.com/31193823/64441274-8d430a00-d09b-11e9-9804-8af4a1c28982.png)

2019-09-06 15:57 UTC, mcrd25 commented on app/views/users/new.html.erb
> +<% if false %>
This is a neat way of not showing these forms. Even though the instructions say to comment it out. I'd accept this ✔️ .

Very clever 😄

2019-09-06 15:57 UTC, mcrd25 commented on app/controllers/users_controller.rb
> +    @user = User.new(name: '', email: '', password: '')
could simply have `@user = User.new`

2019-09-08 10:29 UTC, mosaaleb approved these changes
### Well done @serdg0, @MephistoDevelop :clap:

You can merge to master :+1: 

Good luck with the next projects :computer:

2019-09-09 20:53 UTC, merged